# Generated by Django 5.1.7 on 2025-03-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracaoCargaPontual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_configuracao', models.CharField(default='default', max_length=100)),
                ('token_combinado', models.CharField(max_length=100)),
                ('identificador_empresa', models.IntegerField()),
                ('login_usuario', models.CharField(max_length=100)),
                ('senha_usuario', models.CharField(max_length=100)),
            ],
        ),
    ]
