# Generated by Django 5.1.7 on 2025-03-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_integracaocargapontual'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracaocargapontual',
            name='porta',
            field=models.CharField(default='443', max_length=10),
        ),
        migrations.AddField(
            model_name='integracaocargapontual',
            name='rota_agendamento',
            field=models.CharField(default='/sistema/Integracao/strada_rest_v_100/servidor/v100/agendamento/agendamentoauxiliar100/age_id=', max_length=200),
        ),
        migrations.AddField(
            model_name='integracaocargapontual',
            name='url_base',
            field=models.CharField(default='https://maringaferroliga.cargapontual.com', max_length=200),
        ),
    ]
