# Generated by Django 5.1.7 on 2025-03-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_integracaocargapontual_porta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('mensagem_recebida', models.TextField()),
                ('mensagem_enviada', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='respostaautomatica',
            name='palavra_chave',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='respostaautomatica',
            name='resposta',
            field=models.TextField(help_text='Use {{variaveis}} para dados dinâmicos.'),
        ),
    ]
