# Generated by Django 5.1.7 on 2025-03-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicomensagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaautomatica',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='respostaautomatica',
            name='pergunta_sequencial',
            field=models.CharField(blank=True, help_text='Se necessário, o bot pode perguntar algo antes (ex: Qual o ID do agendamento?)', max_length=200),
        ),
        migrations.AddField(
            model_name='respostaautomatica',
            name='variaveis_disponiveis',
            field=models.TextField(blank=True, help_text='Lista de variáveis possíveis para esta resposta.'),
        ),
        migrations.AlterField(
            model_name='respostaautomatica',
            name='palavra_chave',
            field=models.CharField(help_text='Ex: agendamento, status, chegada', max_length=100),
        ),
        migrations.AlterField(
            model_name='respostaautomatica',
            name='resposta',
            field=models.TextField(help_text='Use {{campos}} para personalizar. Ex: O motorista {{motorista}} está em {{status}}.'),
        ),
    ]
