# Generated by Django 5.1.7 on 2025-03-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_respostaautomatica_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaautomatica',
            name='id_exemplo',
            field=models.CharField(blank=True, help_text='Ex: 84427, usado para consultar exemplo real', max_length=20),
        ),
        migrations.AlterField(
            model_name='respostaautomatica',
            name='palavra_chave',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='respostaautomatica',
            name='pergunta_sequencial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='respostaautomatica',
            name='resposta',
            field=models.TextField(help_text='Use {{variavel}} para montar a resposta.'),
        ),
        migrations.AlterField(
            model_name='respostaautomatica',
            name='variaveis_disponiveis',
            field=models.TextField(blank=True),
        ),
    ]
