# Generated by Django 5.1.7 on 2025-03-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_respostaautomatica_id_exemplo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_menu', models.CharField(help_text='Ex: menu_principal', max_length=100)),
                ('texto', models.TextField(help_text='Texto exibido ao usuário')),
                ('opcao_usuario', models.CharField(blank=True, help_text='Ex: 1, 2... ou vazio para menu direto', max_length=20)),
                ('proximo', models.CharField(help_text='Ex: outro ID de menu, ou acao:nome_da_acao', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
