# Generated by Django 5.1.7 on 2025-04-02 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_menubot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteDeDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('url_base', models.URLField()),
                ('tipo_autenticacao', models.CharField(choices=[('token', 'Token'), ('basic', 'Basic Auth'), ('nenhuma', 'Nenhuma')], default='nenhuma', max_length=20)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('headers_extras', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RegraAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_usuario', models.CharField(max_length=200)),
                ('tipo_comparacao', models.CharField(choices=[('igual', 'Igual'), ('contem', 'Contém')], default='igual', max_length=20)),
                ('contexto', models.CharField(blank=True, max_length=100)),
                ('novo_contexto', models.CharField(blank=True, max_length=100)),
                ('ordem', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='respostaautomatica',
            old_name='ativo',
            new_name='usar_variaveis',
        ),
        migrations.RemoveField(
            model_name='respostaautomatica',
            name='id_exemplo',
        ),
        migrations.RemoveField(
            model_name='respostaautomatica',
            name='palavra_chave',
        ),
        migrations.RemoveField(
            model_name='respostaautomatica',
            name='pergunta_sequencial',
        ),
        migrations.RemoveField(
            model_name='respostaautomatica',
            name='resposta',
        ),
        migrations.RemoveField(
            model_name='respostaautomatica',
            name='variaveis_disponiveis',
        ),
        migrations.AddField(
            model_name='respostaautomatica',
            name='mensagem',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respostaautomatica',
            name='regra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.regraautomatica'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RequisicaoAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('metodo', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=10)),
                ('endpoint', models.CharField(max_length=200)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('retorno_exemplo', models.JSONField(blank=True, default=dict)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fontededados')),
            ],
        ),
        migrations.AddField(
            model_name='regraautomatica',
            name='requisicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.requisicaoapi'),
        ),
        migrations.CreateModel(
            name='VariavelDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('caminho', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requisicaoapi')),
            ],
        ),
    ]
