# Generated by Django 5.1.7 on 2025-04-03 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fontededados_regraautomatica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoAutomatizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('endpoint_api', models.URLField(blank=True, null=True)),
                ('metodo', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10)),
                ('payload_padrao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='regraautomatica',
            name='resposta_padrao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regraautomatica',
            name='contexto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='regraautomatica',
            name='novo_contexto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='regraautomatica',
            name='texto_usuario',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='regraautomatica',
            name='tipo_comparacao',
            field=models.CharField(choices=[('igual', 'Igual'), ('contém', 'Contém')], max_length=20),
        ),
        migrations.AddField(
            model_name='regraautomatica',
            name='acao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.acaoautomatizada'),
        ),
    ]
