# Generated by Django 5.1.7 on 2025-04-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_acaoautomatizada_regraautomatica_resposta_padrao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostaautomatica',
            name='mensagem',
        ),
        migrations.RemoveField(
            model_name='respostaautomatica',
            name='regra',
        ),
        migrations.RemoveField(
            model_name='respostaautomatica',
            name='usar_variaveis',
        ),
        migrations.AddField(
            model_name='respostaautomatica',
            name='palavra_chave',
            field=models.CharField(default='teste', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respostaautomatica',
            name='resposta',
            field=models.TextField(default='teste', help_text='Use {{variaveis}} para dados dinâmicos.'),
            preserve_default=False,
        ),
    ]
