# Generated by Django 5.1.7 on 2025-04-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_respostaautomatica_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('agendamento_id', models.CharField(max_length=50)),
                ('status_atual', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscrição de Notificação',
                'verbose_name_plural': 'Inscrições de Notificação',
            },
        ),
    ]
