# Generated by Django 5.1.7 on 2025-04-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_inscricaonotificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChegadaMotorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('confirmado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
