# Generated by Django 5.1.7 on 2025-04-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_chegadamotorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='chegadamotorista',
            name='ordem_carregamento',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
