# Generated by Django 5.1.7 on 2025-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_chegadamotorista_ordem_carregamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='chegadamotorista',
            name='motorista',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chegadamotorista',
            name='parceiro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chegadamotorista',
            name='status_ordem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chegadamotorista',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
