# Generated by Django 5.1.7 on 2025-04-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_chegadamotorista_motorista_chegadamotorista_parceiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chegadamotorista',
            name='status_ordem_atual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
