# Generated by Django 5.1.7 on 2025-04-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_chegadamotorista_status_ordem_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='chegadamotorista',
            name='periodo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chegadamotorista',
            name='trasnportadora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
