# Generated by Django 5.1.7 on 2025-05-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_trasnportadora_chegadamotorista_transportadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chegadamotorista',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='chegadamotorista',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
