# Generated by Django 5.1.7 on 2025-05-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_chegadamotorista_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chegadamotorista',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
