# Generated by Django 5.1.7 on 2025-05-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_chegadamotorista_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='chegadamotorista',
            name='chegou',
            field=models.BooleanField(default=False),
        ),
    ]
