# Generated by Django 5.1.7 on 2025-05-11 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_chegadamotorista_chegou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chegadamotorista',
            name='confirmado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
